### ISSUE TITLE
event to listen to chat being sent to a player (e.g. from a plugin's command, essentially creating an "API" for all plugins)

### ISSUE THREAD

**Issue by KarolCieslar** [Njol/Skript#243] opened 2013-09-11 17:10 UTC
event to listen to chat being sent to a player (e.g. from a plugin's command, essentially creating an "API" for all plugins)

**Comment by joeuguce99** [comment] 2013-09-12 00:12
You mean like listening to the feedback in chat a command gives after executing?

**Comment by KarolCieslar** [comment] 2013-09-12 14:56
I mean catching a chat message.
example:

Player PLAYER won the game.

When this message is displayed in the chat, the player gets a reward PLAYER. (He is called command)

**Comment by joeuguce99** [comment] 2013-09-13 02:15
So you want to get the feedback of a command, look for a specific word/part in the message, and using it as variable?

**Comment by zmolahah** [comment] 2013-09-13 02:32
something like... 
on chat receive:
    chat message is "Divine_Bliss joined the game"
    broadcast "omgomgomg it's Divine :D!"
Been requested a lot :+1:

**Comment by Njol** [comment] 2013-09-13 09:02
Duplicate of #209

**Closed as completed by Njol** 2013-09-13 09:02 UTC
Labels: duplicate
